<a href="https://colab.research.google.com/github/rajkumar1234-yeddu/DA-matrix-operations-numpy/blob/main/3rdlab_30_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# a
arr1 = np.array([4,5,6,7,8,9])
print(arr1)

x=int(input())
arr2 = arr1+x
print(arr2)

y=int(input())
arr3 = arr1-y
print(arr3)

[4 5 6 7 8 9]
4
[ 8  9 10 11 12 13]
2
[2 3 4 5 6 7]


In [ ]:
# b
arr1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
arr2 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.dot(arr1, arr2))

[[ 1 -7  5]
 [ 5 -1  9]
 [ 2  4  7]]
[[ 1  7 -5]
 [-5  3 -9]
 [-2 -4 -5]]
[[ 0 -7  5]
 [ 5 -2  9]
 [ 2  4  6]]


In [ ]:
# c 1
arr1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

print(arr1.shape)
print(arr1.ndim)

(3, 3)
2


In [ ]:
#c 2
arr1 = np.random.randint(2, size=9)
arr1.reshape((3,3))

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [ ]:
# c 2
arr1 = np.zeros((3,3), dtype=int)
arr2 = np.ones((3,3), dtype=int)

print(arr1)
print()
print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# c 3
arr1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

print(arr1.reshape((1,9)))  #reshape
print()
print(arr1.reshape(-1))  #flatten

[[1 0 0 0 1 0 0 0 1]]

[1 0 0 0 1 0 0 0 1]


In [ ]:
# c 4
arr1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
arr2 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])

print(np.append(arr1, arr2, axis=0))  # Vertically
print()
print(np.append(arr1, arr2, axis=1))  # Horizontally

[[ 1  0  0]
 [ 0  1  0]
 [ 0  0  1]
 [ 0 -7  5]
 [ 5 -2  9]
 [ 2  4  6]]

[[ 1  0  0  0 -7  5]
 [ 0  1  0  5 -2  9]
 [ 0  0  1  2  4  6]]


In [ ]:
# c 5
arr1 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])

print(arr1[0,1])  #element
print(arr1[1])  #row
print(arr1[0:2])  #multiple rows

-7
[ 5 -2  9]
[[ 0 -7  5]
 [ 5 -2  9]]


In [ ]:
# c 6
arr1 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])

print(np.min(arr1))
print(np.max(arr1))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))

-7
9
2.4444444444444446
4.0
4.5487754423241595


In [ ]:
# c 7
arr1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
arr2 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])

print(np.dot(arr1, arr2))

print(arr1*arr2)

[[ 0 -7  5]
 [ 5 -2  9]
 [ 2  4  6]]
[[ 0  0  0]
 [ 0 -2  0]
 [ 0  0  6]]


In [ ]:
# c 8
arr1 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])

eig_val, eig_vec = np.linalg.eig(arr1)
print(eig_val)

[ 9.04028786+0.j         -2.52014393+4.02672667j -2.52014393-4.02672667j]


In [ ]:
# c 9
'''
3 * x0 + x1 = 9, x0 + 2 * x1 = 8 
'''
a = [[3,1], [1,2]]
b = [9,8]
print(np.linalg.solve(a,b))

[2. 3.]


In [ ]:
# c 10
arr1 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])
print(np.linalg.inv(arr1))

[[-0.23529412  0.30392157 -0.25980392]
 [-0.05882353 -0.04901961  0.12254902]
 [ 0.11764706 -0.06862745  0.17156863]]


In [ ]:
# c 11
arr1 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])
print(np.linalg.matrix_rank(arr1))

3


In [ ]:
# c 12
arr1 = np.array([[0, -7, 5], [5, -2, 9], [2, 4, 6]])
print(np.linalg.det(arr1))

203.99999999999994
